export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const SHOW_EDIT_FORM = "SHOW_EDIT_FORM";
export const EDIT_EMPLOYEE_CHOSEN = "EDIT_EMPLOYEE_CHOSEN";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";